<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        $states = [
            ['state' => 'Abia'],
            ['state' => 'Adamawa'],
            ['state' => 'Akwa Ibom'],
            ['state' => 'Anambra'],
            ['state' => 'Bauchi'],
            ['state' => 'Bayelsa'],
            ['state' => 'Benue'],
            ['state' => 'Borno'],
            ['state' => 'Cross River'],
            ['state' => 'Delta'],
            ['state' => 'Ebonyi'],
            ['state' => 'Edo'],
            ['state' => 'Ekiti'],
            ['state' => 'Enugu'],
            ['state' => 'Gombe'],
            ['state' => 'Imo'],
            ['state' => 'Jigawa'],
            ['state' => 'Kaduna'],
            ['state' => 'Kano'],
            ['state' => 'Katsina'],
            ['state' => 'Kebbi'],
            ['state' => 'Kogi'],
            ['state' => 'Kwara'],
            ['state' => 'Lagos'],
            ['state' => 'Nasarawa'],
            ['state' => 'Niger'],
            ['state' => 'Ogun'],
            ['state' => 'Ondo'],
            ['state' => 'Osun'],
            ['state' => 'Oyo'],
            ['state' => 'Plateau'],
            ['state' => 'Rivers'],
            ['state' => 'Sokoto'],
            ['state' => 'Taraba'],
            ['state' => 'Yobe'],
            ['state' => 'Zamfara'],
            ['state' => 'Federal Capital Territory']
        ];

        DB::table('states')->insert($states);


        $lgas = [
            // Paste the SQL insert statements here

            ['state_id' => 1, 'lga_name' => 'Aba North'],
            ['state_id' => 1, 'lga_name' => 'Aba South'],
            ['state_id' => 1, 'lga_name' => 'Arochukwu'],
            ['state_id' => 1, 'lga_name' => 'Bende'],
            ['state_id' => 1, 'lga_name' => 'Ikwuano'],
            ['state_id' => 1, 'lga_name' => 'Isiala Ngwa North'],
            ['state_id' => 1, 'lga_name' => 'Isiala Ngwa South'],
            ['state_id' => 1, 'lga_name' => 'Isuikwuato'],
            ['state_id' => 1, 'lga_name' => 'Obi Ngwa'],
            ['state_id' => 1, 'lga_name' => 'Ohafia'],
            ['state_id' => 1, 'lga_name' => 'Osisioma'],
            ['state_id' => 1, 'lga_name' => 'Ugwunagbo'],
            ['state_id' => 1, 'lga_name' => 'Ukwa East'],
            ['state_id' => 1, 'lga_name' => 'Ukwa West'],
            ['state_id' => 1, 'lga_name' => 'Umuahia North'],
            ['state_id' => 1, 'lga_name' => 'Umuahia South'],
            ['state_id' => 1, 'lga_name' => 'Umu Nneochi'],

            // -- Adamawa
            ['state_id' => 2, 'lga_name' => 'Demsa'],
            ['state_id' => 2, 'lga_name' => 'Fufore'],
            ['state_id' => 2, 'lga_name' => 'Ganye'],
            ['state_id' => 2, 'lga_name' => 'Gayuk'],
            ['state_id' => 2, 'lga_name' => 'Gombi'],
            ['state_id' => 2, 'lga_name' => 'Grie'],
            ['state_id' => 2, 'lga_name' => 'Hong'],
            ['state_id' => 2, 'lga_name' => 'Jada'],
            ['state_id' => 2, 'lga_name' => 'Lamurde'],
            ['state_id' => 2, 'lga_name' => 'Madagali'],
            ['state_id' => 2, 'lga_name' => 'Maiha'],
            ['state_id' => 2, 'lga_name' => 'Mayo-Belwa'],
            ['state_id' => 2, 'lga_name' => 'Michika'],
            ['state_id' => 2, 'lga_name' => 'Mubi North'],
            ['state_id' => 2, 'lga_name' => 'Mubi South'],
            ['state_id' => 2, 'lga_name' => 'Numan'],
            ['state_id' => 2, 'lga_name' => 'Shelleng'],
            ['state_id' => 2, 'lga_name' => 'Song'],
            ['state_id' => 2, 'lga_name' => 'Toungo'],
            ['state_id' => 2, 'lga_name' => 'Yola North'],
            ['state_id' => 2, 'lga_name' => 'Yola South'],

            // -- Akwa Ibom
            ['state_id' => 3, 'lga_name' => 'Abak'],
            ['state_id' => 3, 'lga_name' => 'Eastern Obolo'],
            ['state_id' => 3, 'lga_name' => 'Eket'],
            ['state_id' => 3, 'lga_name' => 'Esit-Eket'],
            ['state_id' => 3, 'lga_name' => 'Essien Udim'],
            ['state_id' => 3, 'lga_name' => 'Etim Ekpo'],
            ['state_id' => 3, 'lga_name' => 'Etinan'],
            ['state_id' => 3, 'lga_name' => 'Ibeno'],
            ['state_id' => 3, 'lga_name' => 'Ibesikpo Asutan'],
            ['state_id' => 3, 'lga_name' => 'Ibiono-Ibom'],
            ['state_id' => 3, 'lga_name' => 'Ika'],
            ['state_id' => 3, 'lga_name' => 'Ikono'],
            ['state_id' => 3, 'lga_name' => 'Ikot Abasi'],
            ['state_id' => 3, 'lga_name' => 'Ikot Ekpene'],
            ['state_id' => 3, 'lga_name' => 'Ini'],
            ['state_id' => 3, 'lga_name' => 'Itu'],
            ['state_id' => 3, 'lga_name' => 'Mbo'],
            ['state_id' => 3, 'lga_name' => 'Mkpat-Enin'],
            ['state_id' => 3, 'lga_name' => 'Nsit-Atai'],
            ['state_id' => 3, 'lga_name' => 'Nsit-Ibom'],
            ['state_id' => 3, 'lga_name' => 'Nsit-Ubium'],
            ['state_id' => 3, 'lga_name' => 'Obot Akara'],
            ['state_id' => 3, 'lga_name' => 'Okobo'],
            ['state_id' => 3, 'lga_name' => 'Onna'],
            ['state_id' => 3, 'lga_name' => 'Oron'],
            ['state_id' => 3, 'lga_name' => 'Oruk Anam'],
            ['state_id' => 3, 'lga_name' => 'Udung-Uko'],
            ['state_id' => 3, 'lga_name' => 'Ukanafun'],
            ['state_id' => 3, 'lga_name' => 'Uruan'],
            ['state_id' => 3, 'lga_name' => 'Urue-Offong/Oruko'],
            ['state_id' => 3, 'lga_name' => 'Uyo'],

            // -- Anambra
            ['state_id' => 4, 'lga_name' => 'Aguata'],
            ['state_id' => 4, 'lga_name' => 'Anambra East'],
            ['state_id' => 4, 'lga_name' => 'Anambra West'],
            ['state_id' => 4, 'lga_name' => 'Anaocha'],
            ['state_id' => 4, 'lga_name' => 'Awka North'],
            ['state_id' => 4, 'lga_name' => 'Awka South'],
            ['state_id' => 4, 'lga_name' => 'Ayamelum'],
            ['state_id' => 4, 'lga_name' => 'Dunukofia'],
            ['state_id' => 4, 'lga_name' => 'Ekwusigo'],
            ['state_id' => 4, 'lga_name' => 'Idemili North'],
            ['state_id' => 4, 'lga_name' => 'Idemili South'],
            ['state_id' => 4, 'lga_name' => 'Ihiala'],
            ['state_id' => 4, 'lga_name' => 'Njikoka'],
            ['state_id' => 4, 'lga_name' => 'Nnewi North'],
            ['state_id' => 4, 'lga_name' => 'Nnewi South'],
            ['state_id' => 4, 'lga_name' => 'Ogbaru'],
            ['state_id' => 4, 'lga_name' => 'Onitsha North'],
            ['state_id' => 4, 'lga_name' => 'Onitsha South'],
            ['state_id' => 4, 'lga_name' => 'Orumba North'],
            ['state_id' => 4, 'lga_name' => 'Orumba South'],
            ['state_id' => 4, 'lga_name' => 'Oyi'],

            // -- Bauchi
            ['state_id' => 5, 'lga_name' => 'Alkaleri'],
            ['state_id' => 5, 'lga_name' => 'Bauchi'],
            ['state_id' => 5, 'lga_name' => 'Bogoro'],
            ['state_id' => 5, 'lga_name' => 'Damban'],
            ['state_id' => 5, 'lga_name' => 'Darazo'],
            ['state_id' => 5, 'lga_name' => 'Dass'],
            ['state_id' => 5, 'lga_name' => 'Ganjuwa'],
            ['state_id' => 5, 'lga_name' => 'Giade'],
            ['state_id' => 5, 'lga_name' => 'Itas/Gadau'],
            ['state_id' => 5, 'lga_name' => 'Jama\'are'],
            ['state_id' => 5, 'lga_name' => 'Katagum'],
            ['state_id' => 5, 'lga_name' => 'Kirfi'],
            ['state_id' => 5, 'lga_name' => 'Misau'],
            ['state_id' => 5, 'lga_name' => 'Ningi'],
            ['state_id' => 5, 'lga_name' => 'Shira'],
            ['state_id' => 5, 'lga_name' => 'Tafawa Balewa'],
            ['state_id' => 5, 'lga_name' => 'Toro'],
            ['state_id' => 5, 'lga_name' => 'Warji'],
            ['state_id' => 5, 'lga_name' => 'Zaki'],

            // -- Bayelsa
            ['state_id' => 6, 'lga_name' => 'Brass'],
            ['state_id' => 6, 'lga_name' => 'Ekeremor'],
            ['state_id' => 6, 'lga_name' => 'Kolokuma/Opokuma'],
            ['state_id' => 6, 'lga_name' => 'Nembe'],
            ['state_id' => 6, 'lga_name' => 'Ogbia'],
            ['state_id' => 6, 'lga_name' => 'Sagbama'],
            ['state_id' => 6, 'lga_name' => 'Southern Ijaw'],
            ['state_id' => 6, 'lga_name' => 'Yenagoa'],

            // -- Benue
            ['state_id' => 7, 'lga_name' => 'Ado'],
            ['state_id' => 7, 'lga_name' => 'Agatu'],
            ['state_id' => 7, 'lga_name' => 'Apa'],
            ['state_id' => 7, 'lga_name' => 'Buruku'],
            ['state_id' => 7, 'lga_name' => 'Gboko'],
            ['state_id' => 7, 'lga_name' => 'Guma'],
            ['state_id' => 7, 'lga_name' => 'Gwer East'],
            ['state_id' => 7, 'lga_name' => 'Gwer West'],
            ['state_id' => 7, 'lga_name' => 'Katsina-Ala'],
            ['state_id' => 7, 'lga_name' => 'Konshisha'],
            ['state_id' => 7, 'lga_name' => 'Kwande'],
            ['state_id' => 7, 'lga_name' => 'Logo'],
            ['state_id' => 7, 'lga_name' => 'Makurdi'],
            ['state_id' => 7, 'lga_name' => 'Obi'],
            ['state_id' => 7, 'lga_name' => 'Ogbadibo'],
            ['state_id' => 7, 'lga_name' => 'Ohimini'],
            ['state_id' => 7, 'lga_name' => 'Oju'],
            ['state_id' => 7, 'lga_name' => 'Okpokwu'],
            ['state_id' => 7, 'lga_name' => 'Otukpo'],
            ['state_id' => 7, 'lga_name' => 'Tarka'],
            ['state_id' => 7, 'lga_name' => 'Ukum'],
            ['state_id' => 7, 'lga_name' => 'Ushongo'],
            ['state_id' => 7, 'lga_name' => 'Vandeikya'],

            // -- Borno
            ['state_id' => 8, 'lga_name' => 'Abadam'],
            ['state_id' => 8, 'lga_name' => 'Askira/Uba'],
            ['state_id' => 8, 'lga_name' => 'Bama'],
            ['state_id' => 8, 'lga_name' => 'Bayo'],
            ['state_id' => 8, 'lga_name' => 'Biu'],
            ['state_id' => 8, 'lga_name' => 'Chibok'],
            ['state_id' => 8, 'lga_name' => 'Damboa'],
            ['state_id' => 8, 'lga_name' => 'Dikwa'],
            ['state_id' => 8, 'lga_name' => 'Gubio'],
            ['state_id' => 8, 'lga_name' => 'Guzamala'],
            ['state_id' => 8, 'lga_name' => 'Gwoza'],
            ['state_id' => 8, 'lga_name' => 'Hawul'],
            ['state_id' => 8, 'lga_name' => 'Jere'],
            ['state_id' => 8, 'lga_name' => 'Kaga'],
            ['state_id' => 8, 'lga_name' => 'Kala/Balge'],
            ['state_id' => 8, 'lga_name' => 'Konduga'],
            ['state_id' => 8, 'lga_name' => 'Kukawa'],
            ['state_id' => 8, 'lga_name' => 'Kwaya Kusar'],
            ['state_id' => 8, 'lga_name' => 'Mafa'],
            ['state_id' => 8, 'lga_name' => 'Magumeri'],
            ['state_id' => 8, 'lga_name' => 'Maiduguri'],
            ['state_id' => 8, 'lga_name' => 'Marte'],
            ['state_id' => 8, 'lga_name' => 'Mobbar'],
            ['state_id' => 8, 'lga_name' => 'Monguno'],
            ['state_id' => 8, 'lga_name' => 'Ngala'],
            ['state_id' => 8, 'lga_name' => 'Nganzai'],
            ['state_id' => 8, 'lga_name' => 'Shani'],

            // -- Cross River
            ['state_id' => 9, 'lga_name' => 'Abi'],
            ['state_id' => 9, 'lga_name' => 'Akamkpa'],
            ['state_id' => 9, 'lga_name' => 'Akpabuyo'],
            ['state_id' => 9, 'lga_name' => 'Bakassi'],
            ['state_id' => 9, 'lga_name' => 'Bekwarra'],
            ['state_id' => 9, 'lga_name' => 'Biase'],
            ['state_id' => 9, 'lga_name' => 'Boki'],
            ['state_id' => 9, 'lga_name' => 'Calabar Municipal'],
            ['state_id' => 9, 'lga_name' => 'Calabar South'],
            ['state_id' => 9, 'lga_name' => 'Etung'],
            ['state_id' => 9, 'lga_name' => 'Ikom'],
            ['state_id' => 9, 'lga_name' => 'Obanliku'],
            ['state_id' => 9, 'lga_name' => 'Obubra'],
            ['state_id' => 9, 'lga_name' => 'Obudu'],
            ['state_id' => 9, 'lga_name' => 'Odukpani'],
            ['state_id' => 9, 'lga_name' => 'Ogoja'],
            ['state_id' => 9, 'lga_name' => 'Yakuur'],
            ['state_id' => 9, 'lga_name' => 'Yala'],

            // -- Delta
            ['state_id' => 10, 'lga_name' => 'Aniocha North'],
            ['state_id' => 10, 'lga_name' => 'Aniocha South'],
            ['state_id' => 10, 'lga_name' => 'Bomadi'],
            ['state_id' => 10, 'lga_name' => 'Burutu'],
            ['state_id' => 10, 'lga_name' => 'Ethiope East'],
            ['state_id' => 10, 'lga_name' => 'Ethiope West'],
            ['state_id' => 10, 'lga_name' => 'Ika North East'],
            ['state_id' => 10, 'lga_name' => 'Ika South'],
            ['state_id' => 10, 'lga_name' => 'Isoko North'],
            ['state_id' => 10, 'lga_name' => 'Isoko South'],
            ['state_id' => 10, 'lga_name' => 'Ndokwa East'],
            ['state_id' => 10, 'lga_name' => 'Ndokwa West'],
            ['state_id' => 10, 'lga_name' => 'Okpe'],
            ['state_id' => 10, 'lga_name' => 'Oshimili North'],
            ['state_id' => 10, 'lga_name' => 'Oshimili South'],
            ['state_id' => 10, 'lga_name' => 'Patani'],
            ['state_id' => 10, 'lga_name' => 'Sapele'],
            ['state_id' => 10, 'lga_name' => 'Udu'],
            ['state_id' => 10, 'lga_name' => 'Ughelli North'],
            ['state_id' => 10, 'lga_name' => 'Ughelli South'],
            ['state_id' => 10, 'lga_name' => 'Ukwuani'],
            ['state_id' => 10, 'lga_name' => 'Uvwie'],
            ['state_id' => 10, 'lga_name' => 'Warri North'],
            ['state_id' => 10, 'lga_name' => 'Warri South'],
            ['state_id' => 10, 'lga_name' => 'Warri South West'],

            // -- Ebonyi
            ['state_id' => 11, 'lga_name' => 'Abakaliki'],
            ['state_id' => 11, 'lga_name' => 'Afikpo North'],
            ['state_id' => 11, 'lga_name' => 'Afikpo South'],
            ['state_id' => 11, 'lga_name' => 'Ebonyi'],
            ['state_id' => 11, 'lga_name' => 'Ezza North'],
            ['state_id' => 11, 'lga_name' => 'Ezza South'],
            ['state_id' => 11, 'lga_name' => 'Ikwo'],
            ['state_id' => 11, 'lga_name' => 'Ishielu'],
            ['state_id' => 11, 'lga_name' => 'Ivo'],
            ['state_id' => 11, 'lga_name' => 'Izzi'],
            ['state_id' => 11, 'lga_name' => 'Ohaozara'],
            ['state_id' => 11, 'lga_name' => 'Ohaukwu'],
            ['state_id' => 11, 'lga_name' => 'Onicha'],

            // -- Edo
            ['state_id' => 12, 'lga_name' => 'Akoko-Edo'],
            ['state_id' => 12, 'lga_name' => 'Egor'],
            ['state_id' => 12, 'lga_name' => 'Esan Central'],
            ['state_id' => 12, 'lga_name' => 'Esan North-East'],
            ['state_id' => 12, 'lga_name' => 'Esan South-East'],
            ['state_id' => 12, 'lga_name' => 'Esan West'],
            ['state_id' => 12, 'lga_name' => 'Etsako Central'],
            ['state_id' => 12, 'lga_name' => 'Etsako East'],
            ['state_id' => 12, 'lga_name' => 'Etsako West'],
            ['state_id' => 12, 'lga_name' => 'Igueben'],
            ['state_id' => 12, 'lga_name' => 'Ikpoba-Okha'],
            ['state_id' => 12, 'lga_name' => 'Oredo'],
            ['state_id' => 12, 'lga_name' => 'Orhionmwon'],
            ['state_id' => 12, 'lga_name' => 'Ovia North-East'],
            ['state_id' => 12, 'lga_name' => 'Ovia South-West'],
            ['state_id' => 12, 'lga_name' => 'Owan East'],
            ['state_id' => 12, 'lga_name' => 'Owan West'],
            ['state_id' => 12, 'lga_name' => 'Uhunmwonde'],

            // -- Ekiti
            ['state_id' => 13, 'lga_name' => 'AdoEkiti'],
            ['state_id' => 13, 'lga_name' => 'Efon'],
            ['state_id' => 13, 'lga_name' => 'Ekiti East'],
            ['state_id' => 13, 'lga_name' => 'Ekiti South-West'],
            ['state_id' => 13, 'lga_name' => 'Ekiti West'],
            ['state_id' => 13, 'lga_name' => 'Emure'],
            ['state_id' => 13, 'lga_name' => 'Gbonyin'],
            ['state_id' => 13, 'lga_name' => 'Ido Osi'],
            ['state_id' => 13, 'lga_name' => 'Ijero'],
            ['state_id' => 13, 'lga_name' => 'Ikere'],
            ['state_id' => 13, 'lga_name' => 'Ikole'],
            ['state_id' => 13, 'lga_name' => 'Ilejemeje'],
            ['state_id' => 13, 'lga_name' => 'Irepodun/Ifelodun'],
            ['state_id' => 13, 'lga_name' => 'Ise/Orun'],
            ['state_id' => 13, 'lga_name' => 'Moba'],
            ['state_id' => 13, 'lga_name' => 'Oye'],

            // -- Enugu
            ['state_id' => 14, 'lga_name' => 'Aninri'],
            ['state_id' => 14, 'lga_name' => 'Awgu'],
            ['state_id' => 14, 'lga_name' => 'Enugu East'],
            ['state_id' => 14, 'lga_name' => 'Enugu North'],
            ['state_id' => 14, 'lga_name' => 'Enugu South'],
            ['state_id' => 14, 'lga_name' => 'Ezeagu'],
            ['state_id' => 14, 'lga_name' => 'Igbo Etiti'],
            ['state_id' => 14, 'lga_name' => 'Igbo Eze North'],
            ['state_id' => 14, 'lga_name' => 'Igbo Eze South'],
            ['state_id' => 14, 'lga_name' => 'Isi Uzo'],
            ['state_id' => 14, 'lga_name' => 'Nkanu East'],
            ['state_id' => 14, 'lga_name' => 'Nkanu West'],
            ['state_id' => 14, 'lga_name' => 'Nsukka'],
            ['state_id' => 14, 'lga_name' => 'Oji River'],
            ['state_id' => 14, 'lga_name' => 'Udenu'],
            ['state_id' => 14, 'lga_name' => 'Udi'],
            ['state_id' => 14, 'lga_name' => 'Uzo Uwani'],

            // -- Gombe
            ['state_id' => 15, 'lga_name' => 'Akko'],
            ['state_id' => 15, 'lga_name' => 'Balanga'],
            ['state_id' => 15, 'lga_name' => 'Billiri'],
            ['state_id' => 15, 'lga_name' => 'Dukku'],
            ['state_id' => 15, 'lga_name' => 'Funakaye'],
            ['state_id' => 15, 'lga_name' => 'Gombe'],
            ['state_id' => 15, 'lga_name' => 'Kaltungo'],
            ['state_id' => 15, 'lga_name' => 'Kwami'],
            ['state_id' => 15, 'lga_name' => 'Nafada'],
            ['state_id' => 15, 'lga_name' => 'Shongom'],
            ['state_id' => 15, 'lga_name' => 'Yamaltu/Deba'],

            // -- Imo
            ['state_id' => 16, 'lga_name' => 'Aboh Mbaise'],
            ['state_id' => 16, 'lga_name' => 'Ahiazu Mbaise'],
            ['state_id' => 16, 'lga_name' => 'Ehime Mbano'],
            ['state_id' => 16, 'lga_name' => 'Ezinihitte'],
            ['state_id' => 16, 'lga_name' => 'Ideato North'],
            ['state_id' => 16, 'lga_name' => 'Ideato South'],
            ['state_id' => 16, 'lga_name' => 'Ihitte/Uboma'],
            ['state_id' => 16, 'lga_name' => 'Ikeduru'],
            ['state_id' => 16, 'lga_name' => 'Isiala Mbano'],
            ['state_id' => 16, 'lga_name' => 'Isu'],
            ['state_id' => 16, 'lga_name' => 'Mbaitoli'],
            ['state_id' => 16, 'lga_name' => 'Ngor Okpala'],
            ['state_id' => 16, 'lga_name' => 'Njaba'],
            ['state_id' => 16, 'lga_name' => 'Nkwerre'],
            ['state_id' => 16, 'lga_name' => 'Nwangele'],
            ['state_id' => 16, 'lga_name' => 'Obowo'],
            ['state_id' => 16, 'lga_name' => 'Oguta'],
            ['state_id' => 16, 'lga_name' => 'Ohaji/Egbema'],
            ['state_id' => 16, 'lga_name' => 'Okigwe'],
            ['state_id' => 16, 'lga_name' => 'Orlu'],
            ['state_id' => 16, 'lga_name' => 'Orsu'],
            ['state_id' => 16, 'lga_name' => 'Oru East'],
            ['state_id' => 16, 'lga_name' => 'Oru West'],
            ['state_id' => 16, 'lga_name' => 'Owerri Municipal'],
            ['state_id' => 16, 'lga_name' => 'Owerri North'],
            ['state_id' => 16, 'lga_name' => 'Owerri West'],

            // -- Jigawa
            ['state_id' => 17, 'lga_name' => 'Auyo'],
            ['state_id' => 17, 'lga_name' => 'Babura'],
            ['state_id' => 17, 'lga_name' => 'Biriniwa'],
            ['state_id' => 17, 'lga_name' => 'Birnin Kudu'],
            ['state_id' => 17, 'lga_name' => 'Buji'],
            ['state_id' => 17, 'lga_name' => 'Dutse'],
            ['state_id' => 17, 'lga_name' => 'Gagarawa'],
            ['state_id' => 17, 'lga_name' => 'Garki'],
            ['state_id' => 17, 'lga_name' => 'Gumel'],
            ['state_id' => 17, 'lga_name' => 'Guri'],
            ['state_id' => 17, 'lga_name' => 'Gwaram'],
            ['state_id' => 17, 'lga_name' => 'Gwiwa'],
            ['state_id' => 17, 'lga_name' => 'Hadejia'],
            ['state_id' => 17, 'lga_name' => 'Jahun'],
            ['state_id' => 17, 'lga_name' => 'Kafin Hausa'],
            ['state_id' => 17, 'lga_name' => 'Kaugama'],
            ['state_id' => 17, 'lga_name' => 'Kazaure'],
            ['state_id' => 17, 'lga_name' => 'Kiri Kasama'],
            ['state_id' => 17, 'lga_name' => 'Kiyawa'],
            ['state_id' => 17, 'lga_name' => 'Maigatari'],
            ['state_id' => 17, 'lga_name' => 'Malam Madori'],
            ['state_id' => 17, 'lga_name' => 'Miga'],
            ['state_id' => 17, 'lga_name' => 'Ringim'],
            ['state_id' => 17, 'lga_name' => 'Roni'],
            ['state_id' => 17, 'lga_name' => 'Sule Tankarkar'],
            ['state_id' => 17, 'lga_name' => 'Taura'],
            ['state_id' => 17, 'lga_name' => 'Yankwashi'],

            // -- Kaduna
            ['state_id' => 18, 'lga_name' => 'Birnin Gwari'],
            ['state_id' => 18, 'lga_name' => 'Chikun'],
            ['state_id' => 18, 'lga_name' => 'Giwa'],
            ['state_id' => 18, 'lga_name' => 'Igabi'],
            ['state_id' => 18, 'lga_name' => 'Ikara'],
            ['state_id' => 18, 'lga_name' => 'Jaba'],
            ['state_id' => 18, 'lga_name' => 'Jema\'a'],
            ['state_id' => 18, 'lga_name' => 'Kachia'],
            ['state_id' => 18, 'lga_name' => 'Kaduna North'],
            ['state_id' => 18, 'lga_name' => 'Kaduna South'],
            ['state_id' => 18, 'lga_name' => 'Kagarko'],
            ['state_id' => 18, 'lga_name' => 'Kajuru'],
            ['state_id' => 18, 'lga_name' => 'Kaura'],
            ['state_id' => 18, 'lga_name' => 'Kauru'],
            ['state_id' => 18, 'lga_name' => 'Kubau'],
            ['state_id' => 18, 'lga_name' => 'Kudan'],
            ['state_id' => 18, 'lga_name' => 'Lere'],
            ['state_id' => 18, 'lga_name' => 'Makarfi'],
            ['state_id' => 18, 'lga_name' => 'Sabon Gari'],
            ['state_id' => 18, 'lga_name' => 'Sanga'],
            ['state_id' => 18, 'lga_name' => 'Soba'],
            ['state_id' => 18, 'lga_name' => 'Zangon Kataf'],
            ['state_id' => 18, 'lga_name' => 'Zaria'],

            // -- Kano
            ['state_id' => 19, 'lga_name' => 'Ajingi'],
            ['state_id' => 19, 'lga_name' => 'Albasu'],
            ['state_id' => 19, 'lga_name' => 'Bagwai'],
            ['state_id' => 19, 'lga_name' => 'Bebeji'],
            ['state_id' => 19, 'lga_name' => 'Bichi'],
            ['state_id' => 19, 'lga_name' => 'Bunkure'],
            ['state_id' => 19, 'lga_name' => 'Dala'],
            ['state_id' => 19, 'lga_name' => 'Dambatta'],
            ['state_id' => 19, 'lga_name' => 'Dawakin Kudu'],
            ['state_id' => 19, 'lga_name' => 'Dawakin Tofa'],
            ['state_id' => 19, 'lga_name' => 'Doguwa'],
            ['state_id' => 19, 'lga_name' => 'Fagge'],
            ['state_id' => 19, 'lga_name' => 'Gabasawa'],
            ['state_id' => 19, 'lga_name' => 'Garko'],
            ['state_id' => 19, 'lga_name' => 'Garun Mallam'],
            ['state_id' => 19, 'lga_name' => 'Gaya'],
            ['state_id' => 19, 'lga_name' => 'Gezawa'],
            ['state_id' => 19, 'lga_name' => 'Gwale'],
            ['state_id' => 19, 'lga_name' => 'Gwarzo'],
            ['state_id' => 19, 'lga_name' => 'Kabo'],
            ['state_id' => 19, 'lga_name' => 'Kano Municipal'],
            ['state_id' => 19, 'lga_name' => 'Karaye'],
            ['state_id' => 19, 'lga_name' => 'Kibiya'],
            ['state_id' => 19, 'lga_name' => 'Kiru'],
            ['state_id' => 19, 'lga_name' => 'Kumbotso'],
            ['state_id' => 19, 'lga_name' => 'Kunchi'],
            ['state_id' => 19, 'lga_name' => 'Kura'],
            ['state_id' => 19, 'lga_name' => 'Madobi'],
            ['state_id' => 19, 'lga_name' => 'Makoda'],
            ['state_id' => 19, 'lga_name' => 'Minjibir'],
            ['state_id' => 19, 'lga_name' => 'Nasarawa'],
            ['state_id' => 19, 'lga_name' => 'Rano'],
            ['state_id' => 19, 'lga_name' => 'Rimin Gado'],
            ['state_id' => 19, 'lga_name' => 'Rogo'],
            ['state_id' => 19, 'lga_name' => 'Shanono'],
            ['state_id' => 19, 'lga_name' => 'Sumaila'],
            ['state_id' => 19, 'lga_name' => 'Takai'],
            ['state_id' => 19, 'lga_name' => 'Tarauni'],
            ['state_id' => 19, 'lga_name' => 'Tofa'],
            ['state_id' => 19, 'lga_name' => 'Tsanyawa'],
            ['state_id' => 19, 'lga_name' => 'Tudun Wada'],
            ['state_id' => 19, 'lga_name' => 'Ungogo'],
            ['state_id' => 19, 'lga_name' => 'Warawa'],
            ['state_id' => 19, 'lga_name' => 'Wudil'],

            // -- Katsina
            ['state_id' => 20, 'lga_name' => 'Bakori'],
            ['state_id' => 20, 'lga_name' => 'Batagarawa'],
            ['state_id' => 20, 'lga_name' => 'Batsari'],
            ['state_id' => 20, 'lga_name' => 'Baure'],
            ['state_id' => 20, 'lga_name' => 'Bindawa'],
            ['state_id' => 20, 'lga_name' => 'Charanchi'],
            ['state_id' => 20, 'lga_name' => 'Dandume'],
            ['state_id' => 20, 'lga_name' => 'Danja'],
            ['state_id' => 20, 'lga_name' => 'Dan Musa'],
            ['state_id' => 20, 'lga_name' => 'Daura'],
            ['state_id' => 20, 'lga_name' => 'Dutsi'],
            ['state_id' => 20, 'lga_name' => 'Dutsin Ma'],
            ['state_id' => 20, 'lga_name' => 'Faskari'],
            ['state_id' => 20, 'lga_name' => 'Funtua'],
            ['state_id' => 20, 'lga_name' => 'Ingawa'],
            ['state_id' => 20, 'lga_name' => 'Jibia'],
            ['state_id' => 20, 'lga_name' => 'Kafur'],
            ['state_id' => 20, 'lga_name' => 'Kaita'],
            ['state_id' => 20, 'lga_name' => 'Kankara'],
            ['state_id' => 20, 'lga_name' => 'Kankia'],
            ['state_id' => 20, 'lga_name' => 'Katsina'],
            ['state_id' => 20, 'lga_name' => 'Kurfi'],
            ['state_id' => 20, 'lga_name' => 'Kusada'],
            ['state_id' => 20, 'lga_name' => 'Mai\'Adua'],
            ['state_id' => 20, 'lga_name' => 'Malumfashi'],
            ['state_id' => 20, 'lga_name' => 'Mani'],
            ['state_id' => 20, 'lga_name' => 'Mashi'],
            ['state_id' => 20, 'lga_name' => 'Matazu'],
            ['state_id' => 20, 'lga_name' => 'Musawa'],
            ['state_id' => 20, 'lga_name' => 'Rimi'],
            ['state_id' => 20, 'lga_name' => 'Sabuwa'],
            ['state_id' => 20, 'lga_name' => 'Safana'],
            ['state_id' => 20, 'lga_name' => 'Sandamu'],
            ['state_id' => 20, 'lga_name' => 'Zango'],

            // -- Kebbi
            ['state_id' => 21, 'lga_name' => 'Aleiro'],
            ['state_id' => 21, 'lga_name' => 'Arewa Dandi'],
            ['state_id' => 21, 'lga_name' => 'Argungu'],
            ['state_id' => 21, 'lga_name' => 'Augie'],
            ['state_id' => 21, 'lga_name' => 'Bagudo'],
            ['state_id' => 21, 'lga_name' => 'Birnin Kebbi'],
            ['state_id' => 21, 'lga_name' => 'Bunza'],
            ['state_id' => 21, 'lga_name' => 'Dandi'],
            ['state_id' => 21, 'lga_name' => 'Fakai'],
            ['state_id' => 21, 'lga_name' => 'Gwandu'],
            ['state_id' => 21, 'lga_name' => 'Jega'],
            ['state_id' => 21, 'lga_name' => 'Kalgo'],
            ['state_id' => 21, 'lga_name' => 'Koko/Besse'],
            ['state_id' => 21, 'lga_name' => 'Maiyama'],
            ['state_id' => 21, 'lga_name' => 'Ngaski'],
            ['state_id' => 21, 'lga_name' => 'Sakaba'],
            ['state_id' => 21, 'lga_name' => 'Shanga'],
            ['state_id' => 21, 'lga_name' => 'Suru'],
            ['state_id' => 21, 'lga_name' => 'Wasagu/Danko'],
            ['state_id' => 21, 'lga_name' => 'Yauri'],
            ['state_id' => 21, 'lga_name' => 'Zuru'],

            // -- Kogi
            ['state_id' => 22, 'lga_name' => 'Adavi'],
            ['state_id' => 22, 'lga_name' => 'Ajaokuta'],
            ['state_id' => 22, 'lga_name' => 'Ankpa'],
            ['state_id' => 22, 'lga_name' => 'Bassa'],
            ['state_id' => 22, 'lga_name' => 'Dekina'],
            ['state_id' => 22, 'lga_name' => 'Ibaji'],
            ['state_id' => 22, 'lga_name' => 'Idah'],
            ['state_id' => 22, 'lga_name' => 'Igalamela Odolu'],
            ['state_id' => 22, 'lga_name' => 'Ijumu'],
            ['state_id' => 22, 'lga_name' => 'Kabba/Bunu'],
            ['state_id' => 22, 'lga_name' => 'Kogi'],
            ['state_id' => 22, 'lga_name' => 'Lokoja'],
            ['state_id' => 22, 'lga_name' => 'Mopa Muro'],
            ['state_id' => 22, 'lga_name' => 'Ofu'],
            ['state_id' => 22, 'lga_name' => 'Ogori/Magongo'],
            ['state_id' => 22, 'lga_name' => 'Okehi'],
            ['state_id' => 22, 'lga_name' => 'Okene'],
            ['state_id' => 22, 'lga_name' => 'Olamaboro'],
            ['state_id' => 22, 'lga_name' => 'Omala'],
            ['state_id' => 22, 'lga_name' => 'Yagba East'],
            ['state_id' => 22, 'lga_name' => 'Yagba West'],

            // -- Kwara
            ['state_id' => 23, 'lga_name' => 'Asa'],
            ['state_id' => 23, 'lga_name' => 'Baruten'],
            ['state_id' => 23, 'lga_name' => 'Edu'],
            ['state_id' => 23, 'lga_name' => 'Ekiti'],
            ['state_id' => 23, 'lga_name' => 'Ifelodun'],
            ['state_id' => 23, 'lga_name' => 'Ilorin East'],
            ['state_id' => 23, 'lga_name' => 'Ilorin South'],
            ['state_id' => 23, 'lga_name' => 'Ilorin West'],
            ['state_id' => 23, 'lga_name' => 'Irepodun'],
            ['state_id' => 23, 'lga_name' => 'Isin'],
            ['state_id' => 23, 'lga_name' => 'Kaiama'],
            ['state_id' => 23, 'lga_name' => 'Moro'],
            ['state_id' => 23, 'lga_name' => 'Offa'],
            ['state_id' => 23, 'lga_name' => 'Oke Ero'],
            ['state_id' => 23, 'lga_name' => 'Oyun'],
            ['state_id' => 23, 'lga_name' => 'Pategi'],

            // -- Lagos
            ['state_id' => 24, 'lga_name' => 'A]ege'],
            ['state_id' => 24, 'lga_name' => 'Ajeromi-Ifelodun'],
            ['state_id' => 24, 'lga_name' => 'Alimosho'],
            ['state_id' => 24, 'lga_name' => 'Amuwo-Odofin'],
            ['state_id' => 24, 'lga_name' => 'Apapa'],
            ['state_id' => 24, 'lga_name' => 'Badagry'],
            ['state_id' => 24, 'lga_name' => 'Epe'],
            ['state_id' => 24, 'lga_name' => 'Eti Osa'],
            ['state_id' => 24, 'lga_name' => 'Ibeju-Lekki'],
            ['state_id' => 24, 'lga_name' => 'Ifako-Ijaiye'],
            ['state_id' => 24, 'lga_name' => 'Ikeja'],
            ['state_id' => 24, 'lga_name' => 'Ikorodu'],
            ['state_id' => 24, 'lga_name' => 'Kosofe'],
            ['state_id' => 24, 'lga_name' => 'Lagos Island'],
            ['state_id' => 24, 'lga_name' => 'Lagos Mainland'],
            ['state_id' => 24, 'lga_name' => 'Mushin'],
            ['state_id' => 24, 'lga_name' => 'Ojo'],
            ['state_id' => 24, 'lga_name' => 'Oshodi-Isolo'],
            ['state_id' => 24, 'lga_name' => 'Shomolu'],
            ['state_id' => 24, 'lga_name' => 'Surulere'],

            // -- Nasarawa
            ['state_id' => 25, 'lga_name' => 'Akwanga'],
            ['state_id' => 25, 'lga_name' => 'Awe'],
            ['state_id' => 25, 'lga_name' => 'Doma'],
            ['state_id' => 25, 'lga_name' => 'Karu'],
            ['state_id' => 25, 'lga_name' => 'Keana'],
            ['state_id' => 25, 'lga_name' => 'Keffi'],
            ['state_id' => 25, 'lga_name' => 'Kokona'],
            ['state_id' => 25, 'lga_name' => 'Lafia'],
            ['state_id' => 25, 'lga_name' => 'Nasarawa'],
            ['state_id' => 25, 'lga_name' => 'Nasarawa Egon'],
            ['state_id' => 25, 'lga_name' => 'Obi'],
            ['state_id' => 25, 'lga_name' => 'Toto'],
            ['state_id' => 25, 'lga_name' => 'Wamba'],

            // -- Niger
            ['state_id' => 26, 'lga_name' => 'Agaie'],
            ['state_id' => 26, 'lga_name' => 'Agwara'],
            ['state_id' => 26, 'lga_name' => 'Bida'],
            ['state_id' => 26, 'lga_name' => 'Borgu'],
            ['state_id' => 26, 'lga_name' => 'Bosso'],
            ['state_id' => 26, 'lga_name' => 'Chanchaga'],
            ['state_id' => 26, 'lga_name' => 'Edati'],
            ['state_id' => 26, 'lga_name' => 'Gbako'],
            ['state_id' => 26, 'lga_name' => 'Gurara'],
            ['state_id' => 26, 'lga_name' => 'Katcha'],
            ['state_id' => 26, 'lga_name' => 'Kontagora'],
            ['state_id' => 26, 'lga_name' => 'Lapai'],
            ['state_id' => 26, 'lga_name' => 'Lavun'],
            ['state_id' => 26, 'lga_name' => 'Magama'],
            ['state_id' => 26, 'lga_name' => 'Mariga'],
            ['state_id' => 26, 'lga_name' => 'Mashegu'],
            ['state_id' => 26, 'lga_name' => 'Mokwa'],
            ['state_id' => 26, 'lga_name' => 'Muya'],
            ['state_id' => 26, 'lga_name' => 'Paikoro'],
            ['state_id' => 26, 'lga_name' => 'Rafi'],
            ['state_id' => 26, 'lga_name' => 'Rijau'],
            ['state_id' => 26, 'lga_name' => 'Shiroro'],
            ['state_id' => 26, 'lga_name' => 'Suleja'],
            ['state_id' => 26, 'lga_name' => 'Tafa'],
            ['state_id' => 26, 'lga_name' => 'Wushishi'],

            // -- Ogun
            ['state_id' => 27, 'lga_name' => 'Abeokuta North'],
            ['state_id' => 27, 'lga_name' => 'Abeokuta South'],
            ['state_id' => 27, 'lga_name' => 'Ado-Odo/Ota'],
            ['state_id' => 27, 'lga_name' => 'Egbado North'],
            ['state_id' => 27, 'lga_name' => 'Egbado South'],
            ['state_id' => 27, 'lga_name' => 'Ewekoro'],
            ['state_id' => 27, 'lga_name' => 'Ifo'],
            ['state_id' => 27, 'lga_name' => 'Ijebu East'],
            ['state_id' => 27, 'lga_name' => 'Ijebu North'],
            ['state_id' => 27, 'lga_name' => 'Ijebu North East'],
            ['state_id' => 27, 'lga_name' => 'Ijebu Ode'],
            ['state_id' => 27, 'lga_name' => 'Ikenne'],
            ['state_id' => 27, 'lga_name' => 'Imeko Afon'],
            ['state_id' => 27, 'lga_name' => 'Ipokia'],
            ['state_id' => 27, 'lga_name' => 'Obafemi Owode'],
            ['state_id' => 27, 'lga_name' => 'Odeda'],
            ['state_id' => 27, 'lga_name' => 'Odogbolu'],
            ['state_id' => 27, 'lga_name' => 'Ogun Waterside'],
            ['state_id' => 27, 'lga_name' => 'Remo North'],
            ['state_id' => 27, 'lga_name' => 'Shagamu'],

            // -- Ondo
            ['state_id' => 28, 'lga_name' => 'Akoko North-East'],
            ['state_id' => 28, 'lga_name' => 'Akoko North-West'],
            ['state_id' => 28, 'lga_name' => 'Akoko South-East'],
            ['state_id' => 28, 'lga_name' => 'Akoko South-West'],
            ['state_id' => 28, 'lga_name' => 'Akure North'],
            ['state_id' => 28, 'lga_name' => 'Akure South'],
            ['state_id' => 28, 'lga_name' => 'Ese Odo'],
            ['state_id' => 28, 'lga_name' => 'Idanre'],
            ['state_id' => 28, 'lga_name' => 'Ifedore'],
            ['state_id' => 28, 'lga_name' => 'Ilaje'],
            ['state_id' => 28, 'lga_name' => 'Ile Oluji/Okeigbo'],
            ['state_id' => 28, 'lga_name' => 'Irele'],
            ['state_id' => 28, 'lga_name' => 'Odigbo'],
            ['state_id' => 28, 'lga_name' => 'Okitipupa'],
            ['state_id' => 28, 'lga_name' => 'Ondo East'],
            ['state_id' => 28, 'lga_name' => 'Ondo West'],
            ['state_id' => 28, 'lga_name' => 'Ose'],
            ['state_id' => 28, 'lga_name' => 'Owo'],

            // -- Osun
            ['state_id' => 29, 'lga_name' => 'Aiyedaade'],
            ['state_id' => 29, 'lga_name' => 'Aiyedire'],
            ['state_id' => 29, 'lga_name' => 'Atakunmosa East'],
            ['state_id' => 29, 'lga_name' => 'Atakunmosa West'],
            ['state_id' => 29, 'lga_name' => 'Boluwaduro'],
            ['state_id' => 29, 'lga_name' => 'Boripe'],
            ['state_id' => 29, 'lga_name' => 'Ede North'],
            ['state_id' => 29, 'lga_name' => 'Ede South'],
            ['state_id' => 29, 'lga_name' => 'Egbedore'],
            ['state_id' => 29, 'lga_name' => 'Ejigbo'],
            ['state_id' => 29, 'lga_name' => 'Ife Central'],
            ['state_id' => 29, 'lga_name' => 'Ife East'],
            ['state_id' => 29, 'lga_name' => 'Ife North'],
            ['state_id' => 29, 'lga_name' => 'Ife South'],
            ['state_id' => 29, 'lga_name' => 'Ifedayo'],
            ['state_id' => 29, 'lga_name' => 'Ifelodun'],
            ['state_id' => 29, 'lga_name' => 'Ila'],
            ['state_id' => 29, 'lga_name' => 'Ilesa East'],
            ['state_id' => 29, 'lga_name' => 'Ilesa West'],
            ['state_id' => 29, 'lga_name' => 'Irepodun'],
            ['state_id' => 29, 'lga_name' => 'Irewole'],
            ['state_id' => 29, 'lga_name' => 'Isokan'],
            ['state_id' => 29, 'lga_name' => 'Iwo'],
            ['state_id' => 29, 'lga_name' => 'Obokun'],
            ['state_id' => 29, 'lga_name' => 'Odo Otin'],
            ['state_id' => 29, 'lga_name' => 'Ola Oluwa'],
            ['state_id' => 29, 'lga_name' => 'Olorunda'],
            ['state_id' => 29, 'lga_name' => 'Oriade'],
            ['state_id' => 29, 'lga_name' => 'Orolu'],
            ['state_id' => 29, 'lga_name' => 'Osogbo'],

            // -- Oyo
            ['state_id' => 30, 'lga_name' => 'Afijio'],
            ['state_id' => 30, 'lga_name' => 'Akinyele'],
            ['state_id' => 30, 'lga_name' => 'Atiba'],
            ['state_id' => 30, 'lga_name' => 'Atisbo'],
            ['state_id' => 30, 'lga_name' => 'Egbeda'],
            ['state_id' => 30, 'lga_name' => 'Ibadan North'],
            ['state_id' => 30, 'lga_name' => 'Ibadan North-East'],
            ['state_id' => 30, 'lga_name' => 'Ibadan North-West'],
            ['state_id' => 30, 'lga_name' => 'Ibadan South-East'],
            ['state_id' => 30, 'lga_name' => 'Ibadan South-West'],
            ['state_id' => 30, 'lga_name' => 'Ibarapa Central'],
            ['state_id' => 30, 'lga_name' => 'Ibarapa East'],
            ['state_id' => 30, 'lga_name' => 'Ibarapa North'],
            ['state_id' => 30, 'lga_name' => 'Ido'],
            ['state_id' => 30, 'lga_name' => 'Irepo'],
            ['state_id' => 30, 'lga_name' => 'Iseyin'],
            ['state_id' => 30, 'lga_name' => 'Itesiwaju'],
            ['state_id' => 30, 'lga_name' => 'Iwajowa'],
            ['state_id' => 30, 'lga_name' => 'Kajola'],
            ['state_id' => 30, 'lga_name' => 'Lagelu'],
            ['state_id' => 30, 'lga_name' => 'Ogbomosho North'],
            ['state_id' => 30, 'lga_name' => 'Ogbomosho South'],
            ['state_id' => 30, 'lga_name' => 'Ogo Oluwa'],
            ['state_id' => 30, 'lga_name' => 'Olorunsogo'],
            ['state_id' => 30, 'lga_name' => 'Oluyole'],
            ['state_id' => 30, 'lga_name' => 'Ona Ara'],
            ['state_id' => 30, 'lga_name' => 'Orelope'],
            ['state_id' => 30, 'lga_name' => 'Ori Ire'],
            ['state_id' => 30, 'lga_name' => 'Oyo East'],
            ['state_id' => 30, 'lga_name' => 'Oyo West'],
            ['state_id' => 30, 'lga_name' => 'Saki East'],
            ['state_id' => 30, 'lga_name' => 'Saki West'],
            ['state_id' => 30, 'lga_name' => 'Surulere'],

            // -- Plateau
            ['state_id' => 31, 'lga_name' => 'Barkin Ladi'],
            ['state_id' => 31, 'lga_name' => 'Bassa'],
            ['state_id' => 31, 'lga_name' => 'Bokkos'],
            ['state_id' => 31, 'lga_name' => 'Jos East'],
            ['state_id' => 31, 'lga_name' => 'Jos North'],
            ['state_id' => 31, 'lga_name' => 'Jos South'],
            ['state_id' => 31, 'lga_name' => 'Kanam'],
            ['state_id' => 31, 'lga_name' => 'Kanke'],
            ['state_id' => 31, 'lga_name' => 'Langtang North'],
            ['state_id' => 31, 'lga_name' => 'Langtang South'],
            ['state_id' => 31, 'lga_name' => 'Mangu'],
            ['state_id' => 31, 'lga_name' => 'Mikang'],
            ['state_id' => 31, 'lga_name' => 'Pankshin'],
            ['state_id' => 31, 'lga_name' => 'Qua\'an Pan'],
            ['state_id' => 31, 'lga_name' => 'Riyom'],
            ['state_id' => 31, 'lga_name' => 'Shendam'],
            ['state_id' => 31, 'lga_name' => 'Wase'],

            // -- Rivers
            ['state_id' => 32, 'lga_name' => 'Abua/Odual'],
            ['state_id' => 32, 'lga_name' => 'Ahoada East'],
            ['state_id' => 32, 'lga_name' => 'Ahoada West'],
            ['state_id' => 32, 'lga_name' => 'Akuku-Toru'],
            ['state_id' => 32, 'lga_name' => 'Andoni'],
            ['state_id' => 32, 'lga_name' => 'Asari-Toru'],
            ['state_id' => 32, 'lga_name' => 'Bonny'],
            ['state_id' => 32, 'lga_name' => 'Degema'],
            ['state_id' => 32, 'lga_name' => 'Eleme'],
            ['state_id' => 32, 'lga_name' => 'Emohua'],
            ['state_id' => 32, 'lga_name' => 'Etche'],
            ['state_id' => 32, 'lga_name' => 'Gokana'],
            ['state_id' => 32, 'lga_name' => 'Ikwerre'],
            ['state_id' => 32, 'lga_name' => 'Khana'],
            ['state_id' => 32, 'lga_name' => 'Obio/Akpor'],
            ['state_id' => 32, 'lga_name' => 'Ogba/Egbema/Ndoni'],
            ['state_id' => 32, 'lga_name' => 'Ogu/Bolo'],
            ['state_id' => 32, 'lga_name' => 'Okrika'],
            ['state_id' => 32, 'lga_name' => 'Omuma'],
            ['state_id' => 32, 'lga_name' => 'Opobo/Nkoro'],
            ['state_id' => 32, 'lga_name' => 'Oyigbo'],
            ['state_id' => 32, 'lga_name' => 'Port Harcourt'],
            ['state_id' => 32, 'lga_name' => 'Tai'],

            // -- Sokoto
            ['state_id' => 33, 'lga_name' => 'Binji'],
            ['state_id' => 33, 'lga_name' => 'Bodinga'],
            ['state_id' => 33, 'lga_name' => 'Dange Shuni'],
            ['state_id' => 33, 'lga_name' => 'Gada'],
            ['state_id' => 33, 'lga_name' => 'Goronyo'],
            ['state_id' => 33, 'lga_name' => 'Gudu'],
            ['state_id' => 33, 'lga_name' => 'Gwadabawa'],
            ['state_id' => 33, 'lga_name' => 'Illela'],
            ['state_id' => 33, 'lga_name' => 'Isa'],
            ['state_id' => 33, 'lga_name' => 'Kebbe'],
            ['state_id' => 33, 'lga_name' => 'Kware'],
            ['state_id' => 33, 'lga_name' => 'Rabah'],
            ['state_id' => 33, 'lga_name' => 'Sabon Birni'],
            ['state_id' => 33, 'lga_name' => 'Shagari'],
            ['state_id' => 33, 'lga_name' => 'Silame'],
            ['state_id' => 33, 'lga_name' => 'Sokoto North'],
            ['state_id' => 33, 'lga_name' => 'Sokoto South'],
            ['state_id' => 33, 'lga_name' => 'Tambuwal'],
            ['state_id' => 33, 'lga_name' => 'Tangaza'],
            ['state_id' => 33, 'lga_name' => 'Tureta'],
            ['state_id' => 33, 'lga_name' => 'Wamako'],
            ['state_id' => 33, 'lga_name' => 'Wurno'],
            ['state_id' => 33, 'lga_name' => 'Yabo'],

            // -- Taraba
            ['state_id' => 34, 'lga_name' => 'Ardo Kola'],
            ['state_id' => 34, 'lga_name' => 'Bali'],
            ['state_id' => 34, 'lga_name' => 'Donga'],
            ['state_id' => 34, 'lga_name' => 'Gashaka'],
            ['state_id' => 34, 'lga_name' => 'Gassol'],
            ['state_id' => 34, 'lga_name' => 'Ibi'],
            ['state_id' => 34, 'lga_name' => 'Jalingo'],
            ['state_id' => 34, 'lga_name' => 'Karim Lamido'],
            ['state_id' => 34, 'lga_name' => 'Kumi'],
            ['state_id' => 34, 'lga_name' => 'Lau'],
            ['state_id' => 34, 'lga_name' => 'Sardauna'],
            ['state_id' => 34, 'lga_name' => 'Takum'],
            ['state_id' => 34, 'lga_name' => 'Ussa'],
            ['state_id' => 34, 'lga_name' => 'Wukari'],
            ['state_id' => 34, 'lga_name' => 'Yorro'],
            ['state_id' => 34, 'lga_name' => 'Zing'],

            // -- Yobe
            ['state_id' => 35, 'lga_name' => 'Bade'],
            ['state_id' => 35, 'lga_name' => 'Bursari'],
            ['state_id' => 35, 'lga_name' => 'Damaturu'],
            ['state_id' => 35, 'lga_name' => 'Fika'],
            ['state_id' => 35, 'lga_name' => 'Fune'],
            ['state_id' => 35, 'lga_name' => 'Geidam'],
            ['state_id' => 35, 'lga_name' => 'Gujba'],
            ['state_id' => 35, 'lga_name' => 'Gulani'],
            ['state_id' => 35, 'lga_name' => 'Jakusko'],
            ['state_id' => 35, 'lga_name' => 'Karasuwa'],
            ['state_id' => 35, 'lga_name' => 'Machina'],
            ['state_id' => 35, 'lga_name' => 'Nangere'],
            ['state_id' => 35, 'lga_name' => 'Nguru'],
            ['state_id' => 35, 'lga_name' => 'Potiskum'],
            ['state_id' => 35, 'lga_name' => 'Tarmuwa'],
            ['state_id' => 35, 'lga_name' => 'Yunusari'],
            ['state_id' => 35, 'lga_name' => 'Yusufari'],

            // -- Zamfara
            ['state_id' => 36, 'lga_name' => 'Anka'],
            ['state_id' => 36, 'lga_name' => 'Bakura'],
            ['state_id' => 36, 'lga_name' => 'Birnin Magaji/Kiyaw'],
            ['state_id' => 36, 'lga_name' => 'Bukkuyum'],
            ['state_id' => 36, 'lga_name' => 'Bungudu'],
            ['state_id' => 36, 'lga_name' => 'Gummi'],
            ['state_id' => 36, 'lga_name' => 'Gusau'],
            ['state_id' => 36, 'lga_name' => 'Kaura Namoda'],
            ['state_id' => 36, 'lga_name' => 'Maradun'],
            ['state_id' => 36, 'lga_name' => 'Maru'],
            ['state_id' => 36, 'lga_name' => 'Shinkafi'],
            ['state_id' => 36, 'lga_name' => 'Talata Mafara'],
            ['state_id' => 36, 'lga_name' => 'Chafe'],
            ['state_id' => 36, 'lga_name' => 'Zurmi'],

            ['state_id' => 37, 'lga_name' => 'Abaji'],
            ['state_id' => 37, 'lga_name' => 'Abuja Municipal Area Council'],
            ['state_id' => 37, 'lga_name' => 'Bwari'],
            ['state_id' => 37, 'lga_name' => 'Gwagwalada'],
            ['state_id' => 37, 'lga_name' => 'Kuje'],
            ['state_id' => 37, 'lga_name' => 'Kwali'],

        ];

        // Insert data into the database
        DB::table('lgas')->insert($lgas);

        $bloodGroup = [
            ['blood_name' => 'A+'],
            ['blood_name' => 'A-'],
            ['blood_name' => 'B+'],
            ['blood_name' => 'B-'],
            ['blood_name' => 'AB+'],
            ['blood_name' => 'AB-'],
            ['blood_name' => 'O+'],
            ['blood_name' => 'O-']
        ];


        // Insert data into the database
        DB::table('bloods')->insert($bloodGroup);
    }
}



// INSERT INTO lgas (state_id, lga_name) VALUES
// -- Abia
// (1, 'Aba North'),
// (1, 'Aba South'),
// (1, 'Arochukwu'),
// (1, 'Bende'),
// (1, 'Ikwuano'),
// (1, 'Isiala Ngwa North'),
// (1, 'Isiala Ngwa South'),
// (1, 'Isuikwuato'),
// (1, 'Obi Ngwa'),
// (1, 'Ohafia'),
// (1, 'Osisioma'),
// (1, 'Ugwunagbo'),
// (1, 'Ukwa East'),
// (1, 'Ukwa West'),
// (1, 'Umuahia North'),
// (1, 'Umuahia South'),
// (1, 'Umu Nneochi'),

// -- Adamawa
// (2, 'Demsa'),
// (2, 'Fufore'),
// (2, 'Ganye'),
// (2, 'Gayuk'),
// (2, 'Gombi'),
// (2, 'Grie'),
// (2, 'Hong'),
// (2, 'Jada'),
// (2, 'Lamurde'),
// (2, 'Madagali'),
// (2, 'Maiha'),
// (2, 'Mayo-Belwa'),
// (2, 'Michika'),
// (2, 'Mubi North'),
// (2, 'Mubi South'),
// (2, 'Numan'),
// (2, 'Shelleng'),
// (2, 'Song'),
// (2, 'Toungo'),
// (2, 'Yola North'),
// (2, 'Yola South'),

// -- Akwa Ibom
// (3, 'Abak'),
// (3, 'Eastern Obolo'),
// (3, 'Eket'),
// (3, 'Esit-Eket'),
// (3, 'Essien Udim'),
// (3, 'Etim Ekpo'),
// (3, 'Etinan'),
// (3, 'Ibeno'),
// (3, 'Ibesikpo Asutan'),
// (3, 'Ibiono-Ibom'),
// (3, 'Ika'),
// (3, 'Ikono'),
// (3, 'Ikot Abasi'),
// (3, 'Ikot Ekpene'),
// (3, 'Ini'),
// (3, 'Itu'),
// (3, 'Mbo'),
// (3, 'Mkpat-Enin'),
// (3, 'Nsit-Atai'),
// (3, 'Nsit-Ibom'),
// (3, 'Nsit-Ubium'),
// (3, 'Obot Akara'),
// (3, 'Okobo'),
// (3, 'Onna'),
// (3, 'Oron'),
// (3, 'Oruk Anam'),
// (3, 'Udung-Uko'),
// (3, 'Ukanafun'),
// (3, 'Uruan'),
// (3, 'Urue-Offong/Oruko'),
// (3, 'Uyo'),

// -- Anambra
// (4, 'Aguata'),
// (4, 'Anambra East'),
// (4, 'Anambra West'),
// (4, 'Anaocha'),
// (4, 'Awka North'),
// (4, 'Awka South'),
// (4, 'Ayamelum'),
// (4, 'Dunukofia'),
// (4, 'Ekwusigo'),
// (4, 'Idemili North'),
// (4, 'Idemili South'),
// (4, 'Ihiala'),
// (4, 'Njikoka'),
// (4, 'Nnewi North'),
// (4, 'Nnewi South'),
// (4, 'Ogbaru'),
// (4, 'Onitsha North'),
// (4, 'Onitsha South'),
// (4, 'Orumba North'),
// (4, 'Orumba South'),
// (4, 'Oyi'),

// -- Bauchi
// (5, 'Alkaleri'),
// (5, 'Bauchi'),
// (5, 'Bogoro'),
// (5, 'Damban'),
// (5, 'Darazo'),
// (5, 'Dass'),
// (5, 'Ganjuwa'),
// (5, 'Giade'),
// (5, 'Itas/Gadau'),
// (5, 'Jama\'are'),
// (5, 'Katagum'),
// (5, 'Kirfi'),
// (5, 'Misau'),
// (5, 'Ningi'),
// (5, 'Shira'),
// (5, 'Tafawa Balewa'),
// (5, 'Toro'),
// (5, 'Warji'),
// (5, 'Zaki'),

// -- Bayelsa
// (6, 'Brass'),
// (6, 'Ekeremor'),
// (6, 'Kolokuma/Opokuma'),
// (6, 'Nembe'),
// (6, 'Ogbia'),
// (6, 'Sagbama'),
// (6, 'Southern Ijaw'),
// (6, 'Yenagoa'),

// -- Benue
// (7, 'Ado'),
// (7, 'Agatu'),
// (7, 'Apa'),
// (7, 'Buruku'),
// (7, 'Gboko'),
// (7, 'Guma'),
// (7, 'Gwer East'),
// (7, 'Gwer West'),
// (7, 'Katsina-Ala'),
// (7, 'Konshisha'),
// (7, 'Kwande'),
// (7, 'Logo'),
// (7, 'Makurdi'),
// (7, 'Obi'),
// (7, 'Ogbadibo'),
// (7, 'Ohimini'),
// (7, 'Oju'),
// (7, 'Okpokwu'),
// (7, 'Otukpo'),
// (7, 'Tarka'),
// (7, 'Ukum'),
// (7, 'Ushongo'),
// (7, 'Vandeikya'),

// -- Borno
// (8, 'Abadam'),
// (8, 'Askira/Uba'),
// (8, 'Bama'),
// (8, 'Bayo'),
// (8, 'Biu'),
// (8, 'Chibok'),
// (8, 'Damboa'),
// (8, 'Dikwa'),
// (8, 'Gubio'),
// (8, 'Guzamala'),
// (8, 'Gwoza'),
// (8, 'Hawul'),
// (8, 'Jere'),
// (8, 'Kaga'),
// (8, 'Kala/Balge'),
// (8, 'Konduga'),
// (8, 'Kukawa'),
// (8, 'Kwaya Kusar'),
// (8, 'Mafa'),
// (8, 'Magumeri'),
// (8, 'Maiduguri'),
// (8, 'Marte'),
// (8, 'Mobbar'),
// (8, 'Monguno'),
// (8, 'Ngala'),
// (8, 'Nganzai'),
// (8, 'Shani'),

// -- Cross River
// (9, 'Abi'),
// (9, 'Akamkpa'),
// (9, 'Akpabuyo'),
// (9, 'Bakassi'),
// (9, 'Bekwarra'),
// (9, 'Biase'),
// (9, 'Boki'),
// (9, 'Calabar Municipal'),
// (9, 'Calabar South'),
// (9, 'Etung'),
// (9, 'Ikom'),
// (9, 'Obanliku'),
// (9, 'Obubra'),
// (9, 'Obudu'),
// (9, 'Odukpani'),
// (9, 'Ogoja'),
// (9, 'Yakuur'),
// (9, 'Yala'),

// -- Delta
// (10, 'Aniocha North'),
// (10, 'Aniocha South'),
// (10, 'Bomadi'),
// (10, 'Burutu'),
// (10, 'Ethiope East'),
// (10, 'Ethiope West'),
// (10, 'Ika North East'),
// (10, 'Ika South'),
// (10, 'Isoko North'),
// (10, 'Isoko South'),
// (10, 'Ndokwa East'),
// (10, 'Ndokwa West'),
// (10, 'Okpe'),
// (10, 'Oshimili North'),
// (10, 'Oshimili South'),
// (10, 'Patani'),
// (10, 'Sapele'),
// (10, 'Udu'),
// (10, 'Ughelli North'),
// (10, 'Ughelli South'),
// (10, 'Ukwuani'),
// (10, 'Uvwie'),
// (10, 'Warri North'),
// (10, 'Warri South'),
// (10, 'Warri South West'),

// -- Ebonyi
// (11, 'Abakaliki'),
// (11, 'Afikpo North'),
// (11, 'Afikpo South'),
// (11, 'Ebonyi'),
// (11, 'Ezza North'),
// (11, 'Ezza South'),
// (11, 'Ikwo'),
// (11, 'Ishielu'),
// (11, 'Ivo'),
// (11, 'Izzi'),
// (11, 'Ohaozara'),
// (11, 'Ohaukwu'),
// (11, 'Onicha'),

// -- Edo
// (12, 'Akoko-Edo'),
// (12, 'Egor'),
// (12, 'Esan Central'),
// (12, 'Esan North-East'),
// (12, 'Esan South-East'),
// (12, 'Esan West'),
// (12, 'Etsako Central'),
// (12, 'Etsako East'),
// (12, 'Etsako West'),
// (12, 'Igueben'),
// (12, 'Ikpoba-Okha'),
// (12, 'Oredo'),
// (12, 'Orhionmwon'),
// (12, 'Ovia North-East'),
// (12, 'Ovia South-West'),
// (12, 'Owan East'),
// (12, 'Owan West'),
// (12, 'Uhunmwonde'),

// -- Ekiti
// (13, 'Ado-E

// kiti'),
// (13, 'Efon'),
// (13, 'Ekiti East'),
// (13, 'Ekiti South-West'),
// (13, 'Ekiti West'),
// (13, 'Emure'),
// (13, 'Gbonyin'),
// (13, 'Ido Osi'),
// (13, 'Ijero'),
// (13, 'Ikere'),
// (13, 'Ikole'),
// (13, 'Ilejemeje'),
// (13, 'Irepodun/Ifelodun'),
// (13, 'Ise/Orun'),
// (13, 'Moba'),
// (13, 'Oye'),

// -- Enugu
// (14, 'Aninri'),
// (14, 'Awgu'),
// (14, 'Enugu East'),
// (14, 'Enugu North'),
// (14, 'Enugu South'),
// (14, 'Ezeagu'),
// (14, 'Igbo Etiti'),
// (14, 'Igbo Eze North'),
// (14, 'Igbo Eze South'),
// (14, 'Isi Uzo'),
// (14, 'Nkanu East'),
// (14, 'Nkanu West'),
// (14, 'Nsukka'),
// (14, 'Oji River'),
// (14, 'Udenu'),
// (14, 'Udi'),
// (14, 'Uzo Uwani'),

// -- Gombe
// (15, 'Akko'),
// (15, 'Balanga'),
// (15, 'Billiri'),
// (15, 'Dukku'),
// (15, 'Funakaye'),
// (15, 'Gombe'),
// (15, 'Kaltungo'),
// (15, 'Kwami'),
// (15, 'Nafada'),
// (15, 'Shongom'),
// (15, 'Yamaltu/Deba'),

// -- Imo
// (16, 'Aboh Mbaise'),
// (16, 'Ahiazu Mbaise'),
// (16, 'Ehime Mbano'),
// (16, 'Ezinihitte'),
// (16, 'Ideato North'),
// (16, 'Ideato South'),
// (16, 'Ihitte/Uboma'),
// (16, 'Ikeduru'),
// (16, 'Isiala Mbano'),
// (16, 'Isu'),
// (16, 'Mbaitoli'),
// (16, 'Ngor Okpala'),
// (16, 'Njaba'),
// (16, 'Nkwerre'),
// (16, 'Nwangele'),
// (16, 'Obowo'),
// (16, 'Oguta'),
// (16, 'Ohaji/Egbema'),
// (16, 'Okigwe'),
// (16, 'Orlu'),
// (16, 'Orsu'),
// (16, 'Oru East'),
// (16, 'Oru West'),
// (16, 'Owerri Municipal'),
// (16, 'Owerri North'),
// (16, 'Owerri West'),

// -- Jigawa
// (17, 'Auyo'),
// (17, 'Babura'),
// (17, 'Biriniwa'),
// (17, 'Birnin Kudu'),
// (17, 'Buji'),
// (17, 'Dutse'),
// (17, 'Gagarawa'),
// (17, 'Garki'),
// (17, 'Gumel'),
// (17, 'Guri'),
// (17, 'Gwaram'),
// (17, 'Gwiwa'),
// (17, 'Hadejia'),
// (17, 'Jahun'),
// (17, 'Kafin Hausa'),
// (17, 'Kaugama'),
// (17, 'Kazaure'),
// (17, 'Kiri Kasama'),
// (17, 'Kiyawa'),
// (17, 'Maigatari'),
// (17, 'Malam Madori'),
// (17, 'Miga'),
// (17, 'Ringim'),
// (17, 'Roni'),
// (17, 'Sule Tankarkar'),
// (17, 'Taura'),
// (17, 'Yankwashi'),

// -- Kaduna
// (18, 'Birnin Gwari'),
// (18, 'Chikun'),
// (18, 'Giwa'),
// (18, 'Igabi'),
// (18, 'Ikara'),
// (18, 'Jaba'),
// (18, 'Jema\'a'),
// (18, 'Kachia'),
// (18, 'Kaduna North'),
// (18, 'Kaduna South'),
// (18, 'Kagarko'),
// (18, 'Kajuru'),
// (18, 'Kaura'),
// (18, 'Kauru'),
// (18, 'Kubau'),
// (18, 'Kudan'),
// (18, 'Lere'),
// (18, 'Makarfi'),
// (18, 'Sabon Gari'),
// (18, 'Sanga'),
// (18, 'Soba'),
// (18, 'Zangon Kataf'),
// (18, 'Zaria'),

// -- Kano
// (19, 'Ajingi'),
// (19, 'Albasu'),
// (19, 'Bagwai'),
// (19, 'Bebeji'),
// (19, 'Bichi'),
// (19, 'Bunkure'),
// (19, 'Dala'),
// (19, 'Dambatta'),
// (19, 'Dawakin Kudu'),
// (19, 'Dawakin Tofa'),
// (19, 'Doguwa'),
// (19, 'Fagge'),
// (19, 'Gabasawa'),
// (19, 'Garko'),
// (19, 'Garun Mallam'),
// (19, 'Gaya'),
// (19, 'Gezawa'),
// (19, 'Gwale'),
// (19, 'Gwarzo'),
// (19, 'Kabo'),
// (19, 'Kano Municipal'),
// (19, 'Karaye'),
// (19, 'Kibiya'),
// (19, 'Kiru'),
// (19, 'Kumbotso'),
// (19, 'Kunchi'),
// (19, 'Kura'),
// (19, 'Madobi'),
// (19, 'Makoda'),
// (19, 'Minjibir'),
// (19, 'Nasarawa'),
// (19, 'Rano'),
// (19, 'Rimin Gado'),
// (19, 'Rogo'),
// (19, 'Shanono'),
// (19, 'Sumaila'),
// (19, 'Takai'),
// (19, 'Tarauni'),
// (19, 'Tofa'),
// (19, 'Tsanyawa'),
// (19, 'Tudun Wada'),
// (19, 'Ungogo'),
// (19, 'Warawa'),
// (19, 'Wudil'),

// -- Katsina
// (20, 'Bakori'),
// (20, 'Batagarawa'),
// (20, 'Batsari'),
// (20, 'Baure'),
// (20, 'Bindawa'),
// (20, 'Charanchi'),
// (20, 'Dandume'),
// (20, 'Danja'),
// (20, 'Dan Musa'),
// (20, 'Daura'),
// (20, 'Dutsi'),
// (20, 'Dutsin Ma'),
// (20, 'Faskari'),
// (20, 'Funtua'),
// (20, 'Ingawa'),
// (20, 'Jibia'),
// (20, 'Kafur'),
// (20, 'Kaita'),
// (20, 'Kankara'),
// (20, 'Kankia'),
// (20, 'Katsina'),
// (20, 'Kurfi'),
// (20, 'Kusada'),
// (20, 'Mai\'Adua'),
// (20, 'Malumfashi'),
// (20, 'Mani'),
// (20, 'Mashi'),
// (20, 'Matazu'),
// (20, 'Musawa'),
// (20, 'Rimi'),
// (20, 'Sabuwa'),
// (20, 'Safana'),
// (20, 'Sandamu'),
// (20, 'Zango'),

// -- Kebbi
// (21, 'Aleiro'),
// (21, 'Arewa Dandi'),
// (21, 'Argungu'),
// (21, 'Augie'),
// (21, 'Bagudo'),
// (21, 'Birnin Kebbi'),
// (21, 'Bunza'),
// (21, 'Dandi'),
// (21, 'Fakai'),
// (21, 'Gwandu'),
// (21, 'Jega'),
// (21, 'Kalgo'),
// (21, 'Koko/Besse'),
// (21, 'Maiyama'),
// (21, 'Ngaski'),
// (21, 'Sakaba'),
// (21, 'Shanga'),
// (21, 'Suru'),
// (21, 'Wasagu/Danko'),
// (21, 'Yauri'),
// (21, 'Zuru'),

// -- Kogi
// (22, 'Adavi'),
// (22, 'Ajaokuta'),
// (22, 'Ankpa'),
// (22, 'Bassa'),
// (22, 'Dekina'),
// (22, 'Ibaji'),
// (22, 'Idah'),
// (22, 'Igalamela Odolu'),
// (22, 'Ijumu'),
// (22, 'Kabba/Bunu'),
// (22, 'Kogi'),
// (22, 'Lokoja'),
// (22, 'Mopa Muro'),
// (22, 'Ofu'),
// (22, 'Ogori/Magongo'),
// (22, 'Okehi'),
// (22, 'Okene'),
// (22, 'Olamaboro'),
// (22, 'Omala'),
// (22, 'Yagba East'),
// (22, 'Yagba West'),

// -- Kwara
// (23, 'Asa'),
// (23, 'Baruten'),
// (23, 'Edu'),
// (23, 'Ekiti'),
// (23, 'Ifelodun'),
// (23, 'Ilorin East'),
// (23, 'Ilorin South'),
// (23, 'Ilorin West'),
// (23, 'Irepodun'),
// (23, 'Isin'),
// (23, 'Kaiama'),
// (23, 'Moro'),
// (23, 'Offa'),
// (23, 'Oke Ero'),
// (23, 'Oyun'),
// (23, 'Pategi'),

// -- Lagos
// (24, 'Age

// ge'),
// (24, 'Ajeromi-Ifelodun'),
// (24, 'Alimosho'),
// (24, 'Amuwo-Odofin'),
// (24, 'Apapa'),
// (24, 'Badagry'),
// (24, 'Epe'),
// (24, 'Eti Osa'),
// (24, 'Ibeju-Lekki'),
// (24, 'Ifako-Ijaiye'),
// (24, 'Ikeja'),
// (24, 'Ikorodu'),
// (24, 'Kosofe'),
// (24, 'Lagos Island'),
// (24, 'Lagos Mainland'),
// (24, 'Mushin'),
// (24, 'Ojo'),
// (24, 'Oshodi-Isolo'),
// (24, 'Shomolu'),
// (24, 'Surulere'),

// -- Nasarawa
// (25, 'Akwanga'),
// (25, 'Awe'),
// (25, 'Doma'),
// (25, 'Karu'),
// (25, 'Keana'),
// (25, 'Keffi'),
// (25, 'Kokona'),
// (25, 'Lafia'),
// (25, 'Nasarawa'),
// (25, 'Nasarawa Egon'),
// (25, 'Obi'),
// (25, 'Toto'),
// (25, 'Wamba'),

// -- Niger
// (26, 'Agaie'),
// (26, 'Agwara'),
// (26, 'Bida'),
// (26, 'Borgu'),
// (26, 'Bosso'),
// (26, 'Chanchaga'),
// (26, 'Edati'),
// (26, 'Gbako'),
// (26, 'Gurara'),
// (26, 'Katcha'),
// (26, 'Kontagora'),
// (26, 'Lapai'),
// (26, 'Lavun'),
// (26, 'Magama'),
// (26, 'Mariga'),
// (26, 'Mashegu'),
// (26, 'Mokwa'),
// (26, 'Muya'),
// (26, 'Paikoro'),
// (26, 'Rafi'),
// (26, 'Rijau'),
// (26, 'Shiroro'),
// (26, 'Suleja'),
// (26, 'Tafa'),
// (26, 'Wushishi'),

// -- Ogun
// (27, 'Abeokuta North'),
// (27, 'Abeokuta South'),
// (27, 'Ado-Odo/Ota'),
// (27, 'Egbado North'),
// (27, 'Egbado South'),
// (27, 'Ewekoro'),
// (27, 'Ifo'),
// (27, 'Ijebu East'),
// (27, 'Ijebu North'),
// (27, 'Ijebu North East'),
// (27, 'Ijebu Ode'),
// (27, 'Ikenne'),
// (27, 'Imeko Afon'),
// (27, 'Ipokia'),
// (27, 'Obafemi Owode'),
// (27, 'Odeda'),
// (27, 'Odogbolu'),
// (27, 'Ogun Waterside'),
// (27, 'Remo North'),
// (27, 'Shagamu'),

// -- Ondo
// (28, 'Akoko North-East'),
// (28, 'Akoko North-West'),
// (28, 'Akoko South-East'),
// (28, 'Akoko South-West'),
// (28, 'Akure North'),
// (28, 'Akure South'),
// (28, 'Ese Odo'),
// (28, 'Idanre'),
// (28, 'Ifedore'),
// (28, 'Ilaje'),
// (28, 'Ile Oluji/Okeigbo'),
// (28, 'Irele'),
// (28, 'Odigbo'),
// (28, 'Okitipupa'),
// (28, 'Ondo East'),
// (28, 'Ondo West'),
// (28, 'Ose'),
// (28, 'Owo'),

// -- Osun
// (29, 'Aiyedaade'),
// (29, 'Aiyedire'),
// (29, 'Atakunmosa East'),
// (29, 'Atakunmosa West'),
// (29, 'Boluwaduro'),
// (29, 'Boripe'),
// (29, 'Ede North'),
// (29, 'Ede South'),
// (29, 'Egbedore'),
// (29, 'Ejigbo'),
// (29, 'Ife Central'),
// (29, 'Ife East'),
// (29, 'Ife North'),
// (29, 'Ife South'),
// (29, 'Ifedayo'),
// (29, 'Ifelodun'),
// (29, 'Ila'),
// (29, 'Ilesa East'),
// (29, 'Ilesa West'),
// (29, 'Irepodun'),
// (29, 'Irewole'),
// (29, 'Isokan'),
// (29, 'Iwo'),
// (29, 'Obokun'),
// (29, 'Odo Otin'),
// (29, 'Ola Oluwa'),
// (29, 'Olorunda'),
// (29, 'Oriade'),
// (29, 'Orolu'),
// (29, 'Osogbo'),

// -- Oyo
// (30, 'Afijio'),
// (30, 'Akinyele'),
// (30, 'Atiba'),
// (30, 'Atisbo'),
// (30, 'Egbeda'),
// (30, 'Ibadan North'),
// (30, 'Ibadan North-East'),
// (30, 'Ibadan North-West'),
// (30, 'Ibadan South-East'),
// (30, 'Ibadan South-West'),
// (30, 'Ibarapa Central'),
// (30, 'Ibarapa East'),
// (30, 'Ibarapa North'),
// (30, 'Ido'),
// (30, 'Irepo'),
// (30, 'Iseyin'),
// (30, 'Itesiwaju'),
// (30, 'Iwajowa'),
// (30, 'Kajola'),
// (30, 'Lagelu'),
// (30, 'Ogbomosho North'),
// (30, 'Ogbomosho South'),
// (30, 'Ogo Oluwa'),
// (30, 'Olorunsogo'),
// (30, 'Oluyole'),
// (30, 'Ona Ara'),
// (30, 'Orelope'),
// (30, 'Ori Ire'),
// (30, 'Oyo East'),
// (30, 'Oyo West'),
// (30, 'Saki East'),
// (30, 'Saki West'),
// (30, 'Surulere'),

// -- Plateau
// (31, 'Barkin Ladi'),
// (31, 'Bassa'),
// (31, 'Bokkos'),
// (31, 'Jos East'),
// (31, 'Jos North'),
// (31, 'Jos South'),
// (31, 'Kanam'),
// (31, 'Kanke'),
// (31, 'Langtang North'),
// (31, 'Langtang South'),
// (31, 'Mangu'),
// (31, 'Mikang'),
// (31, 'Pankshin'),
// (31, 'Qua\'an Pan'),
// (31, 'Riyom'),
// (31, 'Shendam'),
// (31, 'Wase'),

// -- Rivers
// (32, 'Abua/Odual'),
// (32, 'Ahoada East'),
// (32, 'Ahoada West'),
// (32, 'Akuku-Toru'),
// (32, 'Andoni'),
// (32, 'Asari-Toru'),
// (32, 'Bonny'),
// (32, 'Degema'),
// (32, 'Eleme'),
// (32, 'Emohua'),
// (32, 'Etche'),
// (32, 'Gokana'),
// (32, 'Ikwerre'),
// (32, 'Khana'),
// (32, 'Obio/Akpor'),
// (32, 'Ogba/Egbema/Ndoni'),
// (32, 'Ogu/Bolo'),
// (32, 'Okrika'),
// (32, 'Omuma'),
// (32, 'Opobo/Nkoro'),
// (32, 'Oyigbo'),
// (32, 'Port Harcourt'),
// (32, 'Tai'),

// -- Sokoto
// (33, 'Binji'),
// (33, 'Bodinga'),
// (33, 'Dange Shuni'),
// (33, 'Gada'),
// (33, 'Goronyo'),
// (33, 'Gudu'),
// (33, 'Gwadabawa'),
// (33, 'Illela'),
// (33, 'Isa'),
// (33, 'Kebbe'),
// (33, 'Kware'),
// (33, 'Rabah'),
// (33, 'Sabon Birni'),
// (33, 'Shagari'),
// (33, 'Silame'),
// (33, 'Sokoto North'),
// (33, 'Sokoto South'),
// (33, 'Tambuwal'),
// (33, 'Tangaza'),
// (33, 'Tureta'),
// (33, 'Wamako'),
// (33, 'Wurno'),
// (33, 'Yabo'),

// -- Taraba
// (34, 'Ardo Kola'),
// (34, 'Bali'),
// (34, 'Donga'),
// (34, 'Gashaka'),
// (34, 'Gassol'),
// (34, 'Ibi'),
// (34, 'Jalingo'),
// (34, 'Karim Lamido'),
// (34, 'Kumi'),
// (34, 'Lau'),
// (34, 'Sardauna'),
// (34, 'Takum'),
// (34, 'Ussa'),
// (34, 'Wukari'),
// (34, 'Yorro'),
// (34, 'Zing'),

// -- Yobe
// (35, 'Bade'),
// (35, 'Bursari'),
// (35, 'Damaturu'),
// (35, 'Fika'),
// (35, 'Fune'),
// (35, 'Geidam'),
// (35, 'Gujba'),
// (35, 'Gulani'),
// (35, 'Jakusko'),
// (35, 'Karasuwa'),
// (35, 'Machina'),
// (35, 'Nangere'),
// (35,

//  'Nguru'),
// (35, 'Potiskum'),
// (35, 'Tarmuwa'),
// (35, 'Yunusari'),
// (35, 'Yusufari'),

// -- Zamfara
// (36, 'Anka'),
// (36, 'Bakura'),
// (36, 'Birnin Magaji/Kiyaw'),
// (36, 'Bukkuyum'),
// (36, 'Bungudu'),
// (36, 'Gummi'),
// (36, 'Gusau'),
// (36, 'Kaura Namoda'),
// (36, 'Maradun'),
// (36, 'Maru'),
// (36, 'Shinkafi'),
// (36, 'Talata Mafara'),
// (36, 'Chafe'),
// (36, 'Zurmi'),

// (37, 'Abaji'),
// (37, 'Abuja Municipal Area Council'),
// (37, 'Bwari'),
// (37, 'Gwagwalada'),
// (37, 'Kuje'),
// (37, 'Kwali');




// INSERT INTO blood (blood_name) VALUES
// ('A+'),
// ('A-'),
// ('B+'),
// ('B-'),
// ('AB+'),
// ('AB-'),
// ('O+'),
// ('O-');
